### ISSUE TITLE
I failed to run demp.py because the data folder lost some *.npy file.

### ISSUE THREAD

**Issue by polobymulberry** [sfu-gruvi-3dv/deep_human#4]
Traceback (most recent call last):
  File "demo.py", line 154, in <module>
    depth_gt = np.load(params.test_dir + '/' + index + '_depth.npy')
  File "/home/wuchao/anaconda3/envs/deep_human/lib/python3.5/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/0044_depth.npy'

**Comment by sta105** [comment]
Thank you for pointing out this issue, we will upload 0044_depth.npy soon

**Comment by polobymulberry** [comment]
Not only 0044_depth.npy :)

**Comment by Aniket-Mohanty** [comment]
I am facing the same issue. The missing files are :

- 0004_depth.npy
- 0005_depth.npy
- 0006_depth.npy
- 0007_depth.npy
- 0011_depth.npy
- 0016_depth.npy
- 0018_depth.npy
- 0021_depth.npy
- 0044_depth.npy
- 0045_depth.npy
- 0048_depth.npy
- 0057_depth.npy

Any help would be appreciated.
